#!/usr/bin/env node
/**
 * Counts the project's lines and prints the table a release publishes.
 *
 * Committed as a script so the figure is reproducible and so nobody ever
 * re-derives it by hand: an ad-hoc `git ls-files | xargs wc -l` drops every file
 * that matches no prefix, and a total that quietly loses whole directories is a
 * misrepresentation rather than an approximation.
 *
 * Attribution is per SURVIVING line via `git blame`, never by summing added
 * lines from the log. Churn is not authorship, and a line written and later
 * deleted belongs to nobody.
 */
import { spawnSync } from 'node:child_process'
import { join, dirname, extname } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..')

/** Excluded, and named rather than silently dropped. */
const EXCLUSIONS = [
  { path: 'vendor/', why: 'UniGetUI reference submodule — not this project’s code' },
  { path: 'node_modules/', why: 'dependencies' },
  { path: 'app/build-test/', why: 'compiled test output' },
  { path: 'design/support.js', why: 'generated design-canvas runtime, discarded at build' },
  { path: 'package-lock.json', why: 'lockfile — resolved dependency versions, not code' },
]

const CATEGORIES = [
  // Named explicitly so the checked-in design canvas is visible as a design
  // artifact rather than swelling the source total from an unlabelled bucket.
  // startsWith rather than a pattern: a path-prefix test needs an escaped
  // slash, and a backslash does not survive being written through a shell —
  // it silently became /^design// once already, which matches nothing.
  { name: 'Design reference (not hand-written source)', test: p => p.startsWith('design/') },
  { name: 'Application source', test: p => /^app\/src\//.test(p) && /\.(ts|tsx)$/.test(p) },
  { name: 'Tests', test: p => /^app\/test\//.test(p) && /\.(mjs|ts|tsx)$/.test(p) },
  { name: 'Styles', test: p => /\.css$/.test(p) },
  { name: 'Build & tooling scripts', test: p => /^script\//.test(p) },
  { name: 'Site', test: p => /^site\//.test(p) && /\.(html|js|css)$/.test(p) },
  { name: 'Workflows & config', test: p => /^\.github\//.test(p) || /^[^/]*\.(json|yml|yaml)$/.test(p) },
  { name: 'Documentation', test: p => /\.md$/.test(p) },
  // Generated by script/sync-evidence-manifest.mjs, so it is separated from
  // hand-written source rather than swelling the total unattributed.
  {
    name: 'Generated inventory data',
    test: p => p.startsWith('app/test/fixtures/feature-completeness/'),
  },
]

const AGENT_AUTHORS = [/claude/i, /\[bot\]$/i]

function git(args) {
  const result = spawnSync('git', args, { cwd: repoRoot, encoding: 'utf8', maxBuffer: 1 << 28 })
  if (result.status !== 0) {
    throw new Error(`git ${args.join(' ')} failed: ${result.stderr}`)
  }
  return result.stdout
}

const BINARY = new Set(['.png', '.jpg', '.webp', '.ico', '.woff2', '.ttf', '.zip'])

const tracked = git(['ls-files'])
  .split('\n')
  .map(line => line.trim())
  .filter(line => line.length > 0)
  .filter(path => !BINARY.has(extname(path)))

const excluded = []
const included = []
for (const path of tracked) {
  const hit = EXCLUSIONS.find(rule => path.startsWith(rule.path))
  if (hit) {
    excluded.push(path)
  } else {
    included.push(path)
  }
}

function measure(path) {
  let content
  try {
    content = git(['show', `HEAD:${path}`])
  } catch {
    return null
  }
  const lines = content.replace(/\r\n/g, '\n').split('\n')
  // A trailing newline produces one empty final element that is not a line.
  if (lines.length > 0 && lines[lines.length - 1] === '') {
    lines.pop()
  }
  return { total: lines.length, nonBlank: lines.filter(l => l.trim() !== '').length }
}

const byCategory = new Map()
let projectTotal = 0
let projectNonBlank = 0
const uncategorised = []

for (const path of included) {
  const stats = measure(path)
  if (stats === null) {
    continue
  }
  // A catch-all row, so a file matching no rule is visible rather than lost.
  const category = CATEGORIES.find(c => c.test(path))?.name ?? 'Other'
  if (category === 'Other') {
    uncategorised.push(path)
  }
  const current = byCategory.get(category) ?? { files: 0, total: 0, nonBlank: 0 }
  current.files += 1
  current.total += stats.total
  current.nonBlank += stats.nonBlank
  byCategory.set(category, current)
  projectTotal += stats.total
  projectNonBlank += stats.nonBlank
}

let grandTotal = projectTotal
let excludedTotal = 0
for (const path of excluded) {
  const stats = measure(path)
  if (stats !== null) {
    excludedTotal += stats.total
    grandTotal += stats.total
  }
}

/* ---- attribution by surviving line ---- */

let agentLines = 0
let humanLines = 0
const unknownAuthors = new Set()

for (const path of included) {
  let blame
  try {
    blame = git(['blame', '--line-porcelain', 'HEAD', '--', path])
  } catch {
    continue
  }
  for (const line of blame.split('\n')) {
    if (!line.startsWith('author ')) {
      continue
    }
    const author = line.slice('author '.length).trim()
    if (AGENT_AUTHORS.some(rule => rule.test(author))) {
      agentLines += 1
    } else {
      humanLines += 1
      unknownAuthors.add(author)
    }
  }
}

const attributed = agentLines + humanLines

/* ---- output ---- */

const pad = (text, width) => String(text).padEnd(width)
const padLeft = (text, width) => String(text).padStart(width)

console.log('| Category | Files | Lines | Non-blank |')
console.log('| --- | ---: | ---: | ---: |')
for (const [name, stats] of [...byCategory.entries()].sort((a, b) => b[1].total - a[1].total)) {
  console.log(`| ${pad(name, 24)} | ${padLeft(stats.files, 5)} | ${padLeft(stats.total, 6)} | ${padLeft(stats.nonBlank, 9)} |`)
}
console.log(`| **Project total** | ${padLeft(included.length, 5)} | ${padLeft(projectTotal, 6)} | ${padLeft(projectNonBlank, 9)} |`)
console.log(`| _Excluded (see below)_ | ${padLeft(excluded.length, 5)} | ${padLeft(excludedTotal, 6)} | ${padLeft('—', 9)} |`)
console.log(`| **Grand total** | ${padLeft(tracked.length, 5)} | ${padLeft(grandTotal, 6)} | ${padLeft('—', 9)} |`)

console.log('\n**Excluded from the project total**\n')
for (const rule of EXCLUSIONS) {
  console.log(`- \`${rule.path}\` — ${rule.why}`)
}

console.log('\n**Authorship, by surviving line**\n')
console.log(`- Agent-written: ${agentLines} (${((agentLines / attributed) * 100).toFixed(1)}%)`)
console.log(`- Human-written: ${humanLines} (${((humanLines / attributed) * 100).toFixed(1)}%)`)
console.log(
  '\nAttributed per surviving line with `git blame`, not by summing added lines. ' +
    'A commit counts as agent-written when its author matches a known automation identity.'
)

// The counter's own arithmetic must agree with itself. An unexplained gap
// between two numbers in the same table destroys the credibility of both.
if (attributed !== projectTotal) {
  console.error(
    `\n✖ arithmetic mismatch: blame attributed ${attributed} lines but the ` +
      `file count is ${projectTotal}. Fix the counter before publishing this.`
  )
  process.exit(1)
}

if (uncategorised.length > 0) {
  console.log(`\n_${uncategorised.length} file(s) fell into "Other": ${uncategorised.slice(0, 5).join(', ')}_`)
}
